#Do not edit this file directly. It is generated automagicly.
#If you expierienced problems with plugin includes, just remove everything except the last line with "1;"

use plugins::UPC::UPC;
use plugins::EuroTV::EuroTV;
use plugins::Cyfra::Cyfra;
use plugins::MiGuiaTV::MiGuiaTV;
use plugins::xmltv::xmltv;
use plugins::WP::WP;
use plugins::TelemanPl::TelemanPl;
use plugins::vdr::vdr;
use plugins::TvMovieDe::TvMovieDe;
use plugins::Interia::Interia;

1;
