#Do not edit this file directly. It is generated automagicly.
#If you expierienced problems with plugin includes, just remove everything except the last line with "1;"

use plugins::WP::WP;
use plugins::vdr::vdr;
use plugins::EuroTV::EuroTV;
use plugins::xmltv::xmltv;
use plugins::TvMovieDe::TvMovieDe;
use plugins::Interia::Interia;
use plugins::MiGuiaTV::MiGuiaTV;

1;
